---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    ignore:
      # K8s and operator SDK, we need to handle these manually
      - dependency-name: github.com/operator-framework/*
      - dependency-name: k8s.io/*
      - dependency-name: sigs.k8s.io/*
