---
name: Linting

on:
  pull_request:

jobs:
  gitlint:
    name: Commit Message(s)
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@25a956c84d5dd820d28caab9f86b8d183aeeff3d
        with:
          fetch-depth: 0
      - name: Run gitlint
        run: |
          sudo apt-get update
          sudo apt-get install -y golang gitlint
          go version
          make gitlint
