---
name: Linting

on:
  pull_request:

jobs:
  gitlint:
    name: Commit Message(s)
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@25a956c84d5dd820d28caab9f86b8d183aeeff3d
        with:
          fetch-depth: 0
      - name: Run gitlint
        run: |
          curl -L "https://golang.org/dl/go1.16.6.linux-amd64.tar.gz" | tar -C /usr/local -xzf -
          export PATH=$PATH:/usr/local/go/bin
          sudo apt-get install -y gitlint
          make gitlint
